name: ReanimateMC
main: fr.jachou.reanimatemc.ReanimateMC
version: 1.0
commands:
  luckpermms:
    description: Commande secondaire pour utiliser LuckPerms avec ReanimateMC
  reanimatemc:
    description: Commande principale pour ReanimateMC
    usage: /<command> <reload|revive|knockout|status>
permissions:
  reanimatemc.revive:
    description: Permet de réanimer un joueur
    default: true
  reanimatemc.execute:
    description: Permet d’achever un joueur
    default: true
  reanimatemc.bypass:
    description: Ne passe pas en K.O, meurt directement
    default: op
  reanimatemc.admin:
    description: Accès aux commandes d’administration
    default: op