name: ReanimateMC
version: 'alpha-1.0.1'
main: fr.jachou.reanimatemc.ReanimateMC
description: ReanimateMC plugin for Minecraft
depend: [bStats]
commands:
  reanimate:
    description: Reanimate a dead player
    usage: /<command> <player>
    permission: reanimatemc.reanimate