name: ReanimateMC
main: fr.jachou.reanimatemc.ReanimateMC
version: 1.0
api-version: 1.13
commands:
  reanimatemc:
    description: Commande principale pour ReanimateMC
    usage: /<command> <reload|revive|knockout|status|crawl>
permissions:
  reanimatemc.revive:
    description: Permet de réanimer un joueur
    default: true
  reanimatemc.execute:
    description: Permet d’achever un joueur
    default: true
  reanimatemc.bypass:
    description: Ne passe pas en K.O, meurt directement
    default: op
  reanimatemc.admin:
    description: Accès aux commandes d’administration
    default: op
  reanimatemc.loot:
    description: Permet d’ouvrir l’inventaire d’un joueur KO
    default: op
