name: ReanimateMC
version: 'alpha-1.0.3'
main: fr.jachou.reanimatemc.ReanimateMC
description: ReanimateMC plugin for Minecraft
commands:
  reanimate:
    description: Reanimate a dead player
    usage: /<command> <player>
    permission: reanimatemc.reanimate
  ko:
    description: Knockout a player
    usage: /ko <player>
    permission: reanimatemc.ko